config/routes.rb
Rails.application.routes.draw do
  resources :types do
    resources :businesses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :type

  validates :name, :presence => true
  validates :telenum, :presence => true
  validates :street, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :zip, :presence => true
  validates :email, :presence => true
  validates :website, :presence => true

end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :businesses
  validates :category, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @type = Type.find(params[:type_id])
    @business = @type.businesses.new
  end

  def create
    @type = Type.find(params[:type_id])
    @business = @type.businesses.new(business_params)
    if @type.save
      flash[:notice] = "List successfully added!"
      redirect_to type_path(@business.type)
    else
      render :new
    end
  end

  def edit
    @type = Type.find(params[:type_id])
    @business = Business.find(params[:id])
    render :edit
  end

  def update
    @business = Business.find(params[:id])
    if @business.update(business_params)
      redirect_to type_path(@business.type)
    else
      @type = Type.find(params[:type_id])
      render :edit
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to type_path(@business.type)
  end

private
  def business_params
    params.require(:business).permit(:name,:telenum,:street,:city,:state,:zip,:email,:website)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  def index
    @types = Type.all
    render :index
  end

  def show
    @type = Type.find(params[:id])
    render :show
  end

  def new
    @type = Type.new
    render :new
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      flash[:notice] = "List successfully added!"
      redirect_to types_path
    else
      render :new
    end
  end

  private
    def type_params
      params.require(:type).permit(:category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<%= render('layouts/errors', :object => @business) %>

<%= form_for [@type, @business] do |f| %>
  <div class="form-row">
    <div class="form-group col-4">
      <%= f.label :name %>
      <%= f.text_field :name, :class=>"form-control" %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-4">
      <%= f.label :telenum %>
      <%= f.text_field :telenum, :class=>"form-control" %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-6">
      <%= f.label :street %>
      <%= f.text_field :street , :class => "form-control"%>
    </div>
    <div class="form-group col-6">
      <%= f.label :city %>
      <%= f.text_field :city, :class => "form-control" %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-3">
      <%= f.label :state %>
      <%= f.text_field :state, :class => "form-control" %><br>
    </div>
    <div class="form-group col-3">
      <%= f.label :zip %>
      <%= f.text_field :zip, :class=> "form-control" %><br>
    </div>
  </div>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :website %>
  <%= f.text_field :website %><br>
  <p><%= f.submit :class => "btn btn-success" %></p>
<% end %>

app/views/businesses/edit.html.erb
<h1>Edit Business</h1>

<%= render "form" %>

app/views/businesses/new.html.erb
<h1>New Business for <%= @type.category %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikipages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/types/_form.html.erb
<%= render "layouts/errors", :object => @type %>

<%= form_for @type do |f| %>
  <!-- <%= f.label :category %> -->
  <div class="col-4">
    <div class="input-group">
    <%= f.text_field :category, :placeholder => "Category", :class => "form-control" %>
    <span class="input-group-btn">
      <%= f.submit :class => "btn btn-danger"%>
    </span>
  </div>
  </div>
<% end %>

app/views/types/index.html.erb
<h1>Categories</h1>

<!-- <ul class="list-group">
  <% @types.each do |type| %>
    <li class="list-group-item"><%= link_to type.category, type_path(type) %></li>
  <% end %>
</ul> -->
<div class="row">
  <div class="dropdown col-12">
    <button class="btn btn-primary btn-block btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
      Select A Type
    </button>
    <div class="dropdown-menu col-12">
      <% @types.each do |type| %>
        <a class="dropdown-item" href="<%=type_path(type)%>"><%= type.category %></a>
      <% end %>
    </div>
  </div>
</div>
<div class="row mt-3">
  <div class="col-12">
    <%= link_to "New Category", new_type_path, :class => "btn btn-success btn-block btn-lg" %>
  </div>
</div>

app/views/types/new.html.erb
<h1>New Category</h1>

<%= render "form" %>

app/views/types/show.html.erb
<h1><%= @type.category %></h1>

<% if @type.businesses.any? %>
  <h4>Here are the businesses for this type:</h4>

  <ul class="list-group">
    <% @type.businesses.each do |business| %>
      <li class="list-group-item">
        <%= business.name %> |
        <%= link_to "Edit", edit_type_business_path(@type, business) %> |
        <%= link_to "Delete", type_business_path(@type, business),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
        <ul>
          <li><%= business.street %></li>
          <li><%= business.city + ", " + business.state + " " + business.zip%></li>
          <li><%= business.telenum %></li>
          <li><%= business.email %></li>
          <li><%= business.website %></li>
        </ul>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="text-danger">There are no businesses yet!</p>
<% end %>

<p><%= link_to "Add a business", new_type_business_path(@type) %></p>
<p><%= link_to "Return to categories", types_path%></p>